[project]
name = "systemai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "joblib>=1.5.3",
    "scikit-learn>=1.8.0",
]